// Code generated by ent, DO NOT EDIT.

package achievement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/khang00/health/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Achievement {
	return predicate.Achievement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Achievement {
	return predicate.Achievement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Achievement {
	return predicate.Achievement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Achievement {
	return predicate.Achievement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Achievement {
	return predicate.Achievement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Achievement {
	return predicate.Achievement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Achievement {
	return predicate.Achievement(sql.FieldLTE(FieldID, id))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldStatus, v))
}

// ThumbnailImgURL applies equality check predicate on the "thumbnail_img_url" field. It's identical to ThumbnailImgURLEQ.
func ThumbnailImgURL(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldThumbnailImgURL, v))
}

// BfpGoal applies equality check predicate on the "bfp_goal" field. It's identical to BfpGoalEQ.
func BfpGoal(v float64) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldBfpGoal, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldCreatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Achievement {
	return predicate.Achievement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Achievement {
	return predicate.Achievement(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldContainsFold(FieldStatus, v))
}

// ThumbnailImgURLEQ applies the EQ predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLEQ(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLNEQ applies the NEQ predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLNEQ(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldNEQ(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLIn applies the In predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLIn(vs ...string) predicate.Achievement {
	return predicate.Achievement(sql.FieldIn(FieldThumbnailImgURL, vs...))
}

// ThumbnailImgURLNotIn applies the NotIn predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLNotIn(vs ...string) predicate.Achievement {
	return predicate.Achievement(sql.FieldNotIn(FieldThumbnailImgURL, vs...))
}

// ThumbnailImgURLGT applies the GT predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLGT(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldGT(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLGTE applies the GTE predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLGTE(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldGTE(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLLT applies the LT predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLLT(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldLT(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLLTE applies the LTE predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLLTE(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldLTE(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLContains applies the Contains predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLContains(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldContains(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLHasPrefix applies the HasPrefix predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLHasPrefix(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldHasPrefix(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLHasSuffix applies the HasSuffix predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLHasSuffix(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldHasSuffix(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLEqualFold applies the EqualFold predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLEqualFold(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldEqualFold(FieldThumbnailImgURL, v))
}

// ThumbnailImgURLContainsFold applies the ContainsFold predicate on the "thumbnail_img_url" field.
func ThumbnailImgURLContainsFold(v string) predicate.Achievement {
	return predicate.Achievement(sql.FieldContainsFold(FieldThumbnailImgURL, v))
}

// BfpGoalEQ applies the EQ predicate on the "bfp_goal" field.
func BfpGoalEQ(v float64) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldBfpGoal, v))
}

// BfpGoalNEQ applies the NEQ predicate on the "bfp_goal" field.
func BfpGoalNEQ(v float64) predicate.Achievement {
	return predicate.Achievement(sql.FieldNEQ(FieldBfpGoal, v))
}

// BfpGoalIn applies the In predicate on the "bfp_goal" field.
func BfpGoalIn(vs ...float64) predicate.Achievement {
	return predicate.Achievement(sql.FieldIn(FieldBfpGoal, vs...))
}

// BfpGoalNotIn applies the NotIn predicate on the "bfp_goal" field.
func BfpGoalNotIn(vs ...float64) predicate.Achievement {
	return predicate.Achievement(sql.FieldNotIn(FieldBfpGoal, vs...))
}

// BfpGoalGT applies the GT predicate on the "bfp_goal" field.
func BfpGoalGT(v float64) predicate.Achievement {
	return predicate.Achievement(sql.FieldGT(FieldBfpGoal, v))
}

// BfpGoalGTE applies the GTE predicate on the "bfp_goal" field.
func BfpGoalGTE(v float64) predicate.Achievement {
	return predicate.Achievement(sql.FieldGTE(FieldBfpGoal, v))
}

// BfpGoalLT applies the LT predicate on the "bfp_goal" field.
func BfpGoalLT(v float64) predicate.Achievement {
	return predicate.Achievement(sql.FieldLT(FieldBfpGoal, v))
}

// BfpGoalLTE applies the LTE predicate on the "bfp_goal" field.
func BfpGoalLTE(v float64) predicate.Achievement {
	return predicate.Achievement(sql.FieldLTE(FieldBfpGoal, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Achievement {
	return predicate.Achievement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Achievement {
	return predicate.Achievement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Achievement {
	return predicate.Achievement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Achievement {
	return predicate.Achievement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Achievement {
	return predicate.Achievement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Achievement {
	return predicate.Achievement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Achievement {
	return predicate.Achievement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Achievement {
	return predicate.Achievement(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Achievement {
	return predicate.Achievement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Achievement {
	return predicate.Achievement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Achievement) predicate.Achievement {
	return predicate.Achievement(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Achievement) predicate.Achievement {
	return predicate.Achievement(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Achievement) predicate.Achievement {
	return predicate.Achievement(func(s *sql.Selector) {
		p(s.Not())
	})
}
