// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khang00/health/backend/ent/achievement"
	"github.com/khang00/health/backend/ent/user"
)

// AchievementCreate is the builder for creating a Achievement entity.
type AchievementCreate struct {
	config
	mutation *AchievementMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (ac *AchievementCreate) SetStatus(s string) *AchievementCreate {
	ac.mutation.SetStatus(s)
	return ac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ac *AchievementCreate) SetNillableStatus(s *string) *AchievementCreate {
	if s != nil {
		ac.SetStatus(*s)
	}
	return ac
}

// SetThumbnailImgURL sets the "thumbnail_img_url" field.
func (ac *AchievementCreate) SetThumbnailImgURL(s string) *AchievementCreate {
	ac.mutation.SetThumbnailImgURL(s)
	return ac
}

// SetNillableThumbnailImgURL sets the "thumbnail_img_url" field if the given value is not nil.
func (ac *AchievementCreate) SetNillableThumbnailImgURL(s *string) *AchievementCreate {
	if s != nil {
		ac.SetThumbnailImgURL(*s)
	}
	return ac
}

// SetBfpGoal sets the "bfp_goal" field.
func (ac *AchievementCreate) SetBfpGoal(f float64) *AchievementCreate {
	ac.mutation.SetBfpGoal(f)
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AchievementCreate) SetCreatedAt(t time.Time) *AchievementCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AchievementCreate) SetNillableCreatedAt(t *time.Time) *AchievementCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ac *AchievementCreate) SetUserID(id int) *AchievementCreate {
	ac.mutation.SetUserID(id)
	return ac
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (ac *AchievementCreate) SetNillableUserID(id *int) *AchievementCreate {
	if id != nil {
		ac = ac.SetUserID(*id)
	}
	return ac
}

// SetUser sets the "user" edge to the User entity.
func (ac *AchievementCreate) SetUser(u *User) *AchievementCreate {
	return ac.SetUserID(u.ID)
}

// Mutation returns the AchievementMutation object of the builder.
func (ac *AchievementCreate) Mutation() *AchievementMutation {
	return ac.mutation
}

// Save creates the Achievement in the database.
func (ac *AchievementCreate) Save(ctx context.Context) (*Achievement, error) {
	ac.defaults()
	return withHooks[*Achievement, AchievementMutation](ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AchievementCreate) SaveX(ctx context.Context) *Achievement {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AchievementCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AchievementCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AchievementCreate) defaults() {
	if _, ok := ac.mutation.Status(); !ok {
		v := achievement.DefaultStatus
		ac.mutation.SetStatus(v)
	}
	if _, ok := ac.mutation.ThumbnailImgURL(); !ok {
		v := achievement.DefaultThumbnailImgURL
		ac.mutation.SetThumbnailImgURL(v)
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := achievement.DefaultCreatedAt
		ac.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AchievementCreate) check() error {
	if _, ok := ac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Achievement.status"`)}
	}
	if _, ok := ac.mutation.ThumbnailImgURL(); !ok {
		return &ValidationError{Name: "thumbnail_img_url", err: errors.New(`ent: missing required field "Achievement.thumbnail_img_url"`)}
	}
	if _, ok := ac.mutation.BfpGoal(); !ok {
		return &ValidationError{Name: "bfp_goal", err: errors.New(`ent: missing required field "Achievement.bfp_goal"`)}
	}
	if v, ok := ac.mutation.BfpGoal(); ok {
		if err := achievement.BfpGoalValidator(v); err != nil {
			return &ValidationError{Name: "bfp_goal", err: fmt.Errorf(`ent: validator failed for field "Achievement.bfp_goal": %w`, err)}
		}
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Achievement.created_at"`)}
	}
	return nil
}

func (ac *AchievementCreate) sqlSave(ctx context.Context) (*Achievement, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AchievementCreate) createSpec() (*Achievement, *sqlgraph.CreateSpec) {
	var (
		_node = &Achievement{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(achievement.Table, sqlgraph.NewFieldSpec(achievement.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.Status(); ok {
		_spec.SetField(achievement.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := ac.mutation.ThumbnailImgURL(); ok {
		_spec.SetField(achievement.FieldThumbnailImgURL, field.TypeString, value)
		_node.ThumbnailImgURL = value
	}
	if value, ok := ac.mutation.BfpGoal(); ok {
		_spec.SetField(achievement.FieldBfpGoal, field.TypeFloat64, value)
		_node.BfpGoal = value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(achievement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := ac.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   achievement.UserTable,
			Columns: []string{achievement.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_achievements = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AchievementCreateBulk is the builder for creating many Achievement entities in bulk.
type AchievementCreateBulk struct {
	config
	builders []*AchievementCreate
}

// Save creates the Achievement entities in the database.
func (acb *AchievementCreateBulk) Save(ctx context.Context) ([]*Achievement, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Achievement, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AchievementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AchievementCreateBulk) SaveX(ctx context.Context) []*Achievement {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AchievementCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AchievementCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
