// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khang00/health/backend/ent/meal"
	"github.com/khang00/health/backend/ent/user"
)

// MealCreate is the builder for creating a Meal entity.
type MealCreate struct {
	config
	mutation *MealMutation
	hooks    []Hook
}

// SetMealType sets the "meal_type" field.
func (mc *MealCreate) SetMealType(s string) *MealCreate {
	mc.mutation.SetMealType(s)
	return mc
}

// SetImageURL sets the "image_url" field.
func (mc *MealCreate) SetImageURL(s string) *MealCreate {
	mc.mutation.SetImageURL(s)
	return mc
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (mc *MealCreate) SetNillableImageURL(s *string) *MealCreate {
	if s != nil {
		mc.SetImageURL(*s)
	}
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MealCreate) SetCreatedAt(t time.Time) *MealCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MealCreate) SetNillableCreatedAt(t *time.Time) *MealCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (mc *MealCreate) SetUserID(id int) *MealCreate {
	mc.mutation.SetUserID(id)
	return mc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (mc *MealCreate) SetNillableUserID(id *int) *MealCreate {
	if id != nil {
		mc = mc.SetUserID(*id)
	}
	return mc
}

// SetUser sets the "user" edge to the User entity.
func (mc *MealCreate) SetUser(u *User) *MealCreate {
	return mc.SetUserID(u.ID)
}

// Mutation returns the MealMutation object of the builder.
func (mc *MealCreate) Mutation() *MealMutation {
	return mc.mutation
}

// Save creates the Meal in the database.
func (mc *MealCreate) Save(ctx context.Context) (*Meal, error) {
	mc.defaults()
	return withHooks[*Meal, MealMutation](ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MealCreate) SaveX(ctx context.Context) *Meal {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MealCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MealCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MealCreate) defaults() {
	if _, ok := mc.mutation.ImageURL(); !ok {
		v := meal.DefaultImageURL
		mc.mutation.SetImageURL(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := meal.DefaultCreatedAt
		mc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MealCreate) check() error {
	if _, ok := mc.mutation.MealType(); !ok {
		return &ValidationError{Name: "meal_type", err: errors.New(`ent: missing required field "Meal.meal_type"`)}
	}
	if v, ok := mc.mutation.MealType(); ok {
		if err := meal.MealTypeValidator(v); err != nil {
			return &ValidationError{Name: "meal_type", err: fmt.Errorf(`ent: validator failed for field "Meal.meal_type": %w`, err)}
		}
	}
	if _, ok := mc.mutation.ImageURL(); !ok {
		return &ValidationError{Name: "image_url", err: errors.New(`ent: missing required field "Meal.image_url"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Meal.created_at"`)}
	}
	return nil
}

func (mc *MealCreate) sqlSave(ctx context.Context) (*Meal, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MealCreate) createSpec() (*Meal, *sqlgraph.CreateSpec) {
	var (
		_node = &Meal{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(meal.Table, sqlgraph.NewFieldSpec(meal.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.MealType(); ok {
		_spec.SetField(meal.FieldMealType, field.TypeString, value)
		_node.MealType = value
	}
	if value, ok := mc.mutation.ImageURL(); ok {
		_spec.SetField(meal.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(meal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := mc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   meal.UserTable,
			Columns: []string{meal.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_meals = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MealCreateBulk is the builder for creating many Meal entities in bulk.
type MealCreateBulk struct {
	config
	builders []*MealCreate
}

// Save creates the Meal entities in the database.
func (mcb *MealCreateBulk) Save(ctx context.Context) ([]*Meal, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Meal, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MealMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MealCreateBulk) SaveX(ctx context.Context) []*Meal {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MealCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MealCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
