// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/khang00/health/backend/ent/achievement"
	"github.com/khang00/health/backend/ent/article"
	"github.com/khang00/health/backend/ent/bfpdatapoint"
	"github.com/khang00/health/backend/ent/meal"
	"github.com/khang00/health/backend/ent/schema"
	"github.com/khang00/health/backend/ent/tag"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	achievementFields := schema.Achievement{}.Fields()
	_ = achievementFields
	// achievementDescStatus is the schema descriptor for status field.
	achievementDescStatus := achievementFields[0].Descriptor()
	// achievement.DefaultStatus holds the default value on creation for the status field.
	achievement.DefaultStatus = achievementDescStatus.Default.(string)
	// achievementDescThumbnailImgURL is the schema descriptor for thumbnail_img_url field.
	achievementDescThumbnailImgURL := achievementFields[1].Descriptor()
	// achievement.DefaultThumbnailImgURL holds the default value on creation for the thumbnail_img_url field.
	achievement.DefaultThumbnailImgURL = achievementDescThumbnailImgURL.Default.(string)
	// achievementDescBfpGoal is the schema descriptor for bfp_goal field.
	achievementDescBfpGoal := achievementFields[2].Descriptor()
	// achievement.BfpGoalValidator is a validator for the "bfp_goal" field. It is called by the builders before save.
	achievement.BfpGoalValidator = achievementDescBfpGoal.Validators[0].(func(float64) error)
	// achievementDescCreatedAt is the schema descriptor for created_at field.
	achievementDescCreatedAt := achievementFields[3].Descriptor()
	// achievement.DefaultCreatedAt holds the default value on creation for the created_at field.
	achievement.DefaultCreatedAt = achievementDescCreatedAt.Default.(time.Time)
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescThumbnailImgURL is the schema descriptor for thumbnail_img_url field.
	articleDescThumbnailImgURL := articleFields[0].Descriptor()
	// article.DefaultThumbnailImgURL holds the default value on creation for the thumbnail_img_url field.
	article.DefaultThumbnailImgURL = articleDescThumbnailImgURL.Default.(string)
	// articleDescTitle is the schema descriptor for title field.
	articleDescTitle := articleFields[1].Descriptor()
	// article.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	article.TitleValidator = articleDescTitle.Validators[0].(func(string) error)
	// articleDescCreatedAt is the schema descriptor for created_at field.
	articleDescCreatedAt := articleFields[3].Descriptor()
	// article.DefaultCreatedAt holds the default value on creation for the created_at field.
	article.DefaultCreatedAt = articleDescCreatedAt.Default.(time.Time)
	bfpdatapointFields := schema.BFPDataPoint{}.Fields()
	_ = bfpdatapointFields
	// bfpdatapointDescFatPercentage is the schema descriptor for fat_percentage field.
	bfpdatapointDescFatPercentage := bfpdatapointFields[0].Descriptor()
	// bfpdatapoint.FatPercentageValidator is a validator for the "fat_percentage" field. It is called by the builders before save.
	bfpdatapoint.FatPercentageValidator = bfpdatapointDescFatPercentage.Validators[0].(func(float64) error)
	// bfpdatapointDescTotalWeight is the schema descriptor for total_weight field.
	bfpdatapointDescTotalWeight := bfpdatapointFields[1].Descriptor()
	// bfpdatapoint.TotalWeightValidator is a validator for the "total_weight" field. It is called by the builders before save.
	bfpdatapoint.TotalWeightValidator = bfpdatapointDescTotalWeight.Validators[0].(func(int) error)
	// bfpdatapointDescCreatedAt is the schema descriptor for created_at field.
	bfpdatapointDescCreatedAt := bfpdatapointFields[2].Descriptor()
	// bfpdatapoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	bfpdatapoint.DefaultCreatedAt = bfpdatapointDescCreatedAt.Default.(time.Time)
	mealFields := schema.Meal{}.Fields()
	_ = mealFields
	// mealDescMealType is the schema descriptor for meal_type field.
	mealDescMealType := mealFields[0].Descriptor()
	// meal.MealTypeValidator is a validator for the "meal_type" field. It is called by the builders before save.
	meal.MealTypeValidator = mealDescMealType.Validators[0].(func(string) error)
	// mealDescImageURL is the schema descriptor for image_url field.
	mealDescImageURL := mealFields[1].Descriptor()
	// meal.DefaultImageURL holds the default value on creation for the image_url field.
	meal.DefaultImageURL = mealDescImageURL.Default.(string)
	// mealDescCreatedAt is the schema descriptor for created_at field.
	mealDescCreatedAt := mealFields[2].Descriptor()
	// meal.DefaultCreatedAt holds the default value on creation for the created_at field.
	meal.DefaultCreatedAt = mealDescCreatedAt.Default.(time.Time)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescTagName is the schema descriptor for tag_name field.
	tagDescTagName := tagFields[0].Descriptor()
	// tag.TagNameValidator is a validator for the "tag_name" field. It is called by the builders before save.
	tag.TagNameValidator = tagDescTagName.Validators[0].(func(string) error)
	// tagDescCreatedAt is the schema descriptor for created_at field.
	tagDescCreatedAt := tagFields[1].Descriptor()
	// tag.DefaultCreatedAt holds the default value on creation for the created_at field.
	tag.DefaultCreatedAt = tagDescCreatedAt.Default.(time.Time)
}
