// Code generated by ent, DO NOT EDIT.

package bfpdatapoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/khang00/health/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldLTE(FieldID, id))
}

// FatPercentage applies equality check predicate on the "fat_percentage" field. It's identical to FatPercentageEQ.
func FatPercentage(v float64) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldEQ(FieldFatPercentage, v))
}

// TotalWeight applies equality check predicate on the "total_weight" field. It's identical to TotalWeightEQ.
func TotalWeight(v int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldEQ(FieldTotalWeight, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldEQ(FieldCreatedAt, v))
}

// FatPercentageEQ applies the EQ predicate on the "fat_percentage" field.
func FatPercentageEQ(v float64) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldEQ(FieldFatPercentage, v))
}

// FatPercentageNEQ applies the NEQ predicate on the "fat_percentage" field.
func FatPercentageNEQ(v float64) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldNEQ(FieldFatPercentage, v))
}

// FatPercentageIn applies the In predicate on the "fat_percentage" field.
func FatPercentageIn(vs ...float64) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldIn(FieldFatPercentage, vs...))
}

// FatPercentageNotIn applies the NotIn predicate on the "fat_percentage" field.
func FatPercentageNotIn(vs ...float64) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldNotIn(FieldFatPercentage, vs...))
}

// FatPercentageGT applies the GT predicate on the "fat_percentage" field.
func FatPercentageGT(v float64) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldGT(FieldFatPercentage, v))
}

// FatPercentageGTE applies the GTE predicate on the "fat_percentage" field.
func FatPercentageGTE(v float64) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldGTE(FieldFatPercentage, v))
}

// FatPercentageLT applies the LT predicate on the "fat_percentage" field.
func FatPercentageLT(v float64) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldLT(FieldFatPercentage, v))
}

// FatPercentageLTE applies the LTE predicate on the "fat_percentage" field.
func FatPercentageLTE(v float64) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldLTE(FieldFatPercentage, v))
}

// TotalWeightEQ applies the EQ predicate on the "total_weight" field.
func TotalWeightEQ(v int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldEQ(FieldTotalWeight, v))
}

// TotalWeightNEQ applies the NEQ predicate on the "total_weight" field.
func TotalWeightNEQ(v int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldNEQ(FieldTotalWeight, v))
}

// TotalWeightIn applies the In predicate on the "total_weight" field.
func TotalWeightIn(vs ...int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldIn(FieldTotalWeight, vs...))
}

// TotalWeightNotIn applies the NotIn predicate on the "total_weight" field.
func TotalWeightNotIn(vs ...int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldNotIn(FieldTotalWeight, vs...))
}

// TotalWeightGT applies the GT predicate on the "total_weight" field.
func TotalWeightGT(v int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldGT(FieldTotalWeight, v))
}

// TotalWeightGTE applies the GTE predicate on the "total_weight" field.
func TotalWeightGTE(v int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldGTE(FieldTotalWeight, v))
}

// TotalWeightLT applies the LT predicate on the "total_weight" field.
func TotalWeightLT(v int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldLT(FieldTotalWeight, v))
}

// TotalWeightLTE applies the LTE predicate on the "total_weight" field.
func TotalWeightLTE(v int) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldLTE(FieldTotalWeight, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.BFPDataPoint {
	return predicate.BFPDataPoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BFPDataPoint) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BFPDataPoint) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BFPDataPoint) predicate.BFPDataPoint {
	return predicate.BFPDataPoint(func(s *sql.Selector) {
		p(s.Not())
	})
}
