// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MealsColumns holds the columns for the "meals" table.
	MealsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "meal_type", Type: field.TypeString},
		{Name: "image_url", Type: field.TypeString, Default: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG/440px-Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_meals", Type: field.TypeInt, Nullable: true},
	}
	// MealsTable holds the schema information for the "meals" table.
	MealsTable = &schema.Table{
		Name:       "meals",
		Columns:    MealsColumns,
		PrimaryKey: []*schema.Column{MealsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "meals_users_meals",
				Columns:    []*schema.Column{MealsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MealsTable,
		UsersTable,
	}
)

func init() {
	MealsTable.ForeignKeys[0].RefTable = UsersTable
}
