// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khang00/health/ent/bfpdatapoint"
	"github.com/khang00/health/ent/predicate"
	"github.com/khang00/health/ent/user"
)

// BFPDataPointQuery is the builder for querying BFPDataPoint entities.
type BFPDataPointQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.BFPDataPoint
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BFPDataPointQuery builder.
func (bdpq *BFPDataPointQuery) Where(ps ...predicate.BFPDataPoint) *BFPDataPointQuery {
	bdpq.predicates = append(bdpq.predicates, ps...)
	return bdpq
}

// Limit the number of records to be returned by this query.
func (bdpq *BFPDataPointQuery) Limit(limit int) *BFPDataPointQuery {
	bdpq.ctx.Limit = &limit
	return bdpq
}

// Offset to start from.
func (bdpq *BFPDataPointQuery) Offset(offset int) *BFPDataPointQuery {
	bdpq.ctx.Offset = &offset
	return bdpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bdpq *BFPDataPointQuery) Unique(unique bool) *BFPDataPointQuery {
	bdpq.ctx.Unique = &unique
	return bdpq
}

// Order specifies how the records should be ordered.
func (bdpq *BFPDataPointQuery) Order(o ...OrderFunc) *BFPDataPointQuery {
	bdpq.order = append(bdpq.order, o...)
	return bdpq
}

// QueryUser chains the current query on the "user" edge.
func (bdpq *BFPDataPointQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: bdpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bdpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bdpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(bfpdatapoint.Table, bfpdatapoint.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, bfpdatapoint.UserTable, bfpdatapoint.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(bdpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BFPDataPoint entity from the query.
// Returns a *NotFoundError when no BFPDataPoint was found.
func (bdpq *BFPDataPointQuery) First(ctx context.Context) (*BFPDataPoint, error) {
	nodes, err := bdpq.Limit(1).All(setContextOp(ctx, bdpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bfpdatapoint.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bdpq *BFPDataPointQuery) FirstX(ctx context.Context) *BFPDataPoint {
	node, err := bdpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BFPDataPoint ID from the query.
// Returns a *NotFoundError when no BFPDataPoint ID was found.
func (bdpq *BFPDataPointQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bdpq.Limit(1).IDs(setContextOp(ctx, bdpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bfpdatapoint.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bdpq *BFPDataPointQuery) FirstIDX(ctx context.Context) int {
	id, err := bdpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BFPDataPoint entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BFPDataPoint entity is found.
// Returns a *NotFoundError when no BFPDataPoint entities are found.
func (bdpq *BFPDataPointQuery) Only(ctx context.Context) (*BFPDataPoint, error) {
	nodes, err := bdpq.Limit(2).All(setContextOp(ctx, bdpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bfpdatapoint.Label}
	default:
		return nil, &NotSingularError{bfpdatapoint.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bdpq *BFPDataPointQuery) OnlyX(ctx context.Context) *BFPDataPoint {
	node, err := bdpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BFPDataPoint ID in the query.
// Returns a *NotSingularError when more than one BFPDataPoint ID is found.
// Returns a *NotFoundError when no entities are found.
func (bdpq *BFPDataPointQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bdpq.Limit(2).IDs(setContextOp(ctx, bdpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bfpdatapoint.Label}
	default:
		err = &NotSingularError{bfpdatapoint.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bdpq *BFPDataPointQuery) OnlyIDX(ctx context.Context) int {
	id, err := bdpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BFPDataPoints.
func (bdpq *BFPDataPointQuery) All(ctx context.Context) ([]*BFPDataPoint, error) {
	ctx = setContextOp(ctx, bdpq.ctx, "All")
	if err := bdpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BFPDataPoint, *BFPDataPointQuery]()
	return withInterceptors[[]*BFPDataPoint](ctx, bdpq, qr, bdpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bdpq *BFPDataPointQuery) AllX(ctx context.Context) []*BFPDataPoint {
	nodes, err := bdpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BFPDataPoint IDs.
func (bdpq *BFPDataPointQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bdpq.ctx.Unique == nil && bdpq.path != nil {
		bdpq.Unique(true)
	}
	ctx = setContextOp(ctx, bdpq.ctx, "IDs")
	if err = bdpq.Select(bfpdatapoint.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bdpq *BFPDataPointQuery) IDsX(ctx context.Context) []int {
	ids, err := bdpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bdpq *BFPDataPointQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bdpq.ctx, "Count")
	if err := bdpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bdpq, querierCount[*BFPDataPointQuery](), bdpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bdpq *BFPDataPointQuery) CountX(ctx context.Context) int {
	count, err := bdpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bdpq *BFPDataPointQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bdpq.ctx, "Exist")
	switch _, err := bdpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bdpq *BFPDataPointQuery) ExistX(ctx context.Context) bool {
	exist, err := bdpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BFPDataPointQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bdpq *BFPDataPointQuery) Clone() *BFPDataPointQuery {
	if bdpq == nil {
		return nil
	}
	return &BFPDataPointQuery{
		config:     bdpq.config,
		ctx:        bdpq.ctx.Clone(),
		order:      append([]OrderFunc{}, bdpq.order...),
		inters:     append([]Interceptor{}, bdpq.inters...),
		predicates: append([]predicate.BFPDataPoint{}, bdpq.predicates...),
		withUser:   bdpq.withUser.Clone(),
		// clone intermediate query.
		sql:  bdpq.sql.Clone(),
		path: bdpq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (bdpq *BFPDataPointQuery) WithUser(opts ...func(*UserQuery)) *BFPDataPointQuery {
	query := (&UserClient{config: bdpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bdpq.withUser = query
	return bdpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FatPercentage float64 `json:"fat_percentage,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BFPDataPoint.Query().
//		GroupBy(bfpdatapoint.FieldFatPercentage).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bdpq *BFPDataPointQuery) GroupBy(field string, fields ...string) *BFPDataPointGroupBy {
	bdpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BFPDataPointGroupBy{build: bdpq}
	grbuild.flds = &bdpq.ctx.Fields
	grbuild.label = bfpdatapoint.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FatPercentage float64 `json:"fat_percentage,omitempty"`
//	}
//
//	client.BFPDataPoint.Query().
//		Select(bfpdatapoint.FieldFatPercentage).
//		Scan(ctx, &v)
func (bdpq *BFPDataPointQuery) Select(fields ...string) *BFPDataPointSelect {
	bdpq.ctx.Fields = append(bdpq.ctx.Fields, fields...)
	sbuild := &BFPDataPointSelect{BFPDataPointQuery: bdpq}
	sbuild.label = bfpdatapoint.Label
	sbuild.flds, sbuild.scan = &bdpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BFPDataPointSelect configured with the given aggregations.
func (bdpq *BFPDataPointQuery) Aggregate(fns ...AggregateFunc) *BFPDataPointSelect {
	return bdpq.Select().Aggregate(fns...)
}

func (bdpq *BFPDataPointQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bdpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bdpq); err != nil {
				return err
			}
		}
	}
	for _, f := range bdpq.ctx.Fields {
		if !bfpdatapoint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bdpq.path != nil {
		prev, err := bdpq.path(ctx)
		if err != nil {
			return err
		}
		bdpq.sql = prev
	}
	return nil
}

func (bdpq *BFPDataPointQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BFPDataPoint, error) {
	var (
		nodes       = []*BFPDataPoint{}
		withFKs     = bdpq.withFKs
		_spec       = bdpq.querySpec()
		loadedTypes = [1]bool{
			bdpq.withUser != nil,
		}
	)
	if bdpq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, bfpdatapoint.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BFPDataPoint).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BFPDataPoint{config: bdpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bdpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bdpq.withUser; query != nil {
		if err := bdpq.loadUser(ctx, query, nodes, nil,
			func(n *BFPDataPoint, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bdpq *BFPDataPointQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*BFPDataPoint, init func(*BFPDataPoint), assign func(*BFPDataPoint, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BFPDataPoint)
	for i := range nodes {
		if nodes[i].user_bf_ps == nil {
			continue
		}
		fk := *nodes[i].user_bf_ps
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_bf_ps" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bdpq *BFPDataPointQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bdpq.querySpec()
	_spec.Node.Columns = bdpq.ctx.Fields
	if len(bdpq.ctx.Fields) > 0 {
		_spec.Unique = bdpq.ctx.Unique != nil && *bdpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bdpq.driver, _spec)
}

func (bdpq *BFPDataPointQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bfpdatapoint.Table, bfpdatapoint.Columns, sqlgraph.NewFieldSpec(bfpdatapoint.FieldID, field.TypeInt))
	_spec.From = bdpq.sql
	if unique := bdpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bdpq.path != nil {
		_spec.Unique = true
	}
	if fields := bdpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bfpdatapoint.FieldID)
		for i := range fields {
			if fields[i] != bfpdatapoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bdpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bdpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bdpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bdpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bdpq *BFPDataPointQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bdpq.driver.Dialect())
	t1 := builder.Table(bfpdatapoint.Table)
	columns := bdpq.ctx.Fields
	if len(columns) == 0 {
		columns = bfpdatapoint.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bdpq.sql != nil {
		selector = bdpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bdpq.ctx.Unique != nil && *bdpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bdpq.predicates {
		p(selector)
	}
	for _, p := range bdpq.order {
		p(selector)
	}
	if offset := bdpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bdpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BFPDataPointGroupBy is the group-by builder for BFPDataPoint entities.
type BFPDataPointGroupBy struct {
	selector
	build *BFPDataPointQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bdpgb *BFPDataPointGroupBy) Aggregate(fns ...AggregateFunc) *BFPDataPointGroupBy {
	bdpgb.fns = append(bdpgb.fns, fns...)
	return bdpgb
}

// Scan applies the selector query and scans the result into the given value.
func (bdpgb *BFPDataPointGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bdpgb.build.ctx, "GroupBy")
	if err := bdpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BFPDataPointQuery, *BFPDataPointGroupBy](ctx, bdpgb.build, bdpgb, bdpgb.build.inters, v)
}

func (bdpgb *BFPDataPointGroupBy) sqlScan(ctx context.Context, root *BFPDataPointQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bdpgb.fns))
	for _, fn := range bdpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bdpgb.flds)+len(bdpgb.fns))
		for _, f := range *bdpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bdpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bdpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BFPDataPointSelect is the builder for selecting fields of BFPDataPoint entities.
type BFPDataPointSelect struct {
	*BFPDataPointQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bdps *BFPDataPointSelect) Aggregate(fns ...AggregateFunc) *BFPDataPointSelect {
	bdps.fns = append(bdps.fns, fns...)
	return bdps
}

// Scan applies the selector query and scans the result into the given value.
func (bdps *BFPDataPointSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bdps.ctx, "Select")
	if err := bdps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BFPDataPointQuery, *BFPDataPointSelect](ctx, bdps.BFPDataPointQuery, bdps, bdps.inters, v)
}

func (bdps *BFPDataPointSelect) sqlScan(ctx context.Context, root *BFPDataPointQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bdps.fns))
	for _, fn := range bdps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bdps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bdps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
