// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/khang00/health/ent/meal"
	"github.com/khang00/health/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mealFields := schema.Meal{}.Fields()
	_ = mealFields
	// mealDescMealType is the schema descriptor for meal_type field.
	mealDescMealType := mealFields[0].Descriptor()
	// meal.MealTypeValidator is a validator for the "meal_type" field. It is called by the builders before save.
	meal.MealTypeValidator = mealDescMealType.Validators[0].(func(string) error)
	// mealDescImageURL is the schema descriptor for image_url field.
	mealDescImageURL := mealFields[1].Descriptor()
	// meal.DefaultImageURL holds the default value on creation for the image_url field.
	meal.DefaultImageURL = mealDescImageURL.Default.(string)
	// mealDescCreatedAt is the schema descriptor for created_at field.
	mealDescCreatedAt := mealFields[2].Descriptor()
	// meal.DefaultCreatedAt holds the default value on creation for the created_at field.
	meal.DefaultCreatedAt = mealDescCreatedAt.Default.(time.Time)
}
