// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/khang00/health/ent/bfpdatapoint"
	"github.com/khang00/health/ent/meal"
	"github.com/khang00/health/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bfpdatapointFields := schema.BFPDataPoint{}.Fields()
	_ = bfpdatapointFields
	// bfpdatapointDescFatPercentage is the schema descriptor for fat_percentage field.
	bfpdatapointDescFatPercentage := bfpdatapointFields[0].Descriptor()
	// bfpdatapoint.FatPercentageValidator is a validator for the "fat_percentage" field. It is called by the builders before save.
	bfpdatapoint.FatPercentageValidator = bfpdatapointDescFatPercentage.Validators[0].(func(float64) error)
	// bfpdatapointDescTotalWeight is the schema descriptor for total_weight field.
	bfpdatapointDescTotalWeight := bfpdatapointFields[1].Descriptor()
	// bfpdatapoint.TotalWeightValidator is a validator for the "total_weight" field. It is called by the builders before save.
	bfpdatapoint.TotalWeightValidator = bfpdatapointDescTotalWeight.Validators[0].(func(int) error)
	// bfpdatapointDescCreatedAt is the schema descriptor for created_at field.
	bfpdatapointDescCreatedAt := bfpdatapointFields[2].Descriptor()
	// bfpdatapoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	bfpdatapoint.DefaultCreatedAt = bfpdatapointDescCreatedAt.Default.(time.Time)
	mealFields := schema.Meal{}.Fields()
	_ = mealFields
	// mealDescMealType is the schema descriptor for meal_type field.
	mealDescMealType := mealFields[0].Descriptor()
	// meal.MealTypeValidator is a validator for the "meal_type" field. It is called by the builders before save.
	meal.MealTypeValidator = mealDescMealType.Validators[0].(func(string) error)
	// mealDescImageURL is the schema descriptor for image_url field.
	mealDescImageURL := mealFields[1].Descriptor()
	// meal.DefaultImageURL holds the default value on creation for the image_url field.
	meal.DefaultImageURL = mealDescImageURL.Default.(string)
	// mealDescCreatedAt is the schema descriptor for created_at field.
	mealDescCreatedAt := mealFields[2].Descriptor()
	// meal.DefaultCreatedAt holds the default value on creation for the created_at field.
	meal.DefaultCreatedAt = mealDescCreatedAt.Default.(time.Time)
}
