// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Achievement is the predicate function for achievement builders.
type Achievement func(*sql.Selector)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// BFPDataPoint is the predicate function for bfpdatapoint builders.
type BFPDataPoint func(*sql.Selector)

// Meal is the predicate function for meal builders.
type Meal func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
