// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BFPDataPoint is the predicate function for bfpdatapoint builders.
type BFPDataPoint func(*sql.Selector)

// Meal is the predicate function for meal builders.
type Meal func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
